// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://jrhfuezlhiuhqnqrszao.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpyaGZ1ZXpsaGl1aHFucXJzemFvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM1NDA1MjcsImV4cCI6MjA0OTExNjUyN30.B5Pw24g-tSnvgZNTbRHVI13v8wXfgFb-6pB8Fh2cICA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);